### ISSUE TITLE
关于每次切换节点频繁询问

### ISSUE THREAD

**Issue by Synchronized1** [haishanh/yacd#495]
最新版本中每次切换节点都要询问是否关闭当前节点所有连接,略显繁琐
能否在右上角的设置中加入一个总开关
![image](https://user-images.githubusercontent.com/58451554/84065178-7cdb0980-a9f6-11ea-918f-a3cde032eb49.png)

打开该开关:切换节点将直接关闭占用的连接,之后切换节点的操作均不在给予弹框提示
关闭该开关:每次切换都会提示(默认操作)

**Comment by Cowkine4** [comment]
Well, So closing the old connections manually through an external interface was completely wrong. Both yacd and clash-dashboard were completely doing it the wrong way. 
What surge has done is, when the underlying proxy has changed, the kernel itself should re-establish all connections on the old proxy server to the new one for us, instead of waiting for the client application to fail and then initiate a new connection. That would be way too late.

**Comment by Synchronized1** [comment]
@Cowkine4 yeah,there are still many details that need to be improved at the core of clash.

**Comment by haishanh** [comment]
closing as done

seamless connections closing and re-connect is not what this web app can do.
